### ISSUE TITLE
New RocketChat API changes break RocketChatBot

### ISSUE THREAD

**Issue by tamasgal** [jadolg/RocketChatBot#2]
RocketChat recently changed their API (at least it seems so, by looking at the suddenly occuring error messages) and the bot is not working anymore:

```
KeyError('messages',)
KeyError('messages',)
KeyError('messages',)
KeyError('messages',)
KeyError('messages',)
KeyError('messages',)
KeyError('messages',)
KeyError('messages',)
Traceback (most recent call last):
  File "scripts/chatbot.py", line 160, in <module>
    main()
  File "scripts/chatbot.py", line 156, in main
    run()
  File "scripts/chatbot.py", line 47, in run
    bot.run()
  File "/home/off1user/.pyenv/versions/3.6.1/lib/python3.6/site-packages/RocketChatBot.py", line 135, in run
    for im in self.api.im_list().json().get('ims'):
```

Are there any plans to update this package? I am not sure I'll find time to jump in with a PR 😕

**Comment by jadolg** [comment]
I'm currently working on updating the API wrapper for the new versions.
After the update, I'll take a look.
If you have the time, PRs are appreciated ;)

**Comment by kaiwasaki** [comment]
It's probably due to too many API requests. I created a PR which shows the real error message which comes from the API.

**Comment by jadolg** [comment]
merged

**Comment by lbblitz54** [comment]
Yes turning off the rate limiter in RC settings "fixes" this issue
![image](https://user-images.githubusercontent.com/17748076/77952586-86772100-7291-11ea-97af-1cc030b8c9c7.png)

**Comment by jadolg** [comment]
closed as it was an API limitation issue
