### ISSUE TITLE
retrieve the username and role for the people speak to the robot

### ISSUE THREAD

**Issue by xu4wang** [jadolg/RocketChatBot#7]
Is there a way to get the information regarding the one who is speaking to the robot?

For example, Bob speak in the general channel:

```
Bob:  @robot please what's the weather today?
```

can robot know it's Bob who is asking him, and Bob is with the role "user"?
I am asking because, sometimes, the robot is with many features, and may need to do role based permission control.

BR,Austin

**Comment by jadolg** [comment]
RocketChatBot uses rocketchat_API so you could technically use https://rocket.chat/docs/developer-guides/rest-api/users/info/ to get information about a user. Please notice that the answer to this call is subject to the role of the user making it.
