### ISSUE TITLE
receive direct message

### ISSUE THREAD

**Issue by xu4wang** [jadolg/RocketChatBot#8]
If a Rocket Chat user initiate a direct message to the robot, is there a way for the robot to receive the message in the direct conversation and send reply back?

Thanks,
Austin

**Comment by jadolg** [comment]
for private messages, the API uses the space IM.
[This](https://rocket.chat/docs/developer-guides/rest-api/im/messages/) way you can get the private messages with a specific user by user name or room id and you can use [list](https://rocket.chat/docs/developer-guides/rest-api/im/list/) to get a list of open messages. These endpoints are also subject to your server constraints so there's pagination, limits, and other perks that might not be too straight forward to get in the begining.
